apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.get-admission-PVC.name }}
  namespace: {{ .Values.namespace }}
spec:
  accessModes:
    - {{ .Values.get-admission-PVC.accessMode }}
  storageClassName: {{ .Values.get-admission-PVC.storageClassName }}
  resources:
    requests:
      storage: {{ .Values.get-admission-PVC.size }}