apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.getAdmissionApp.service.name }}
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: {{ .Values.getAdmissionApp.name }}
  ports:
    - port: {{ .Values.getAdmissionApp.service.port }}
      targetPort: {{ .Values.getAdmissionApp.service.targetPort }}
  type: {{ .Values.getAdmissionApp.service.type }}
