apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.mongodb.service.name }}
spec:
  selector:
    app: {{ .Values.mongodb.name }}
  ports:
    - port: {{ .Values.mongodb.service.port }}
      targetPort: {{ .Values.mongodb.containerPort }}
  type: {{ .Values.mongodb.service.type }}
